[package]
name = "typed-builder"
description = "Compile-time type-checked builder derive"
version = "0.1.0"
authors = ["IdanArye <idanarye@gmail.com>"]
license = "MIT"
repository = "https://github.com/idanarye/rust-typed-builder"
documentation = "https://idanarye.github.io/rust-typed-builder/"
readme = "README.md"
keywords = ["builder"]

[lib]
proc-macro = true

[dependencies]
syn = "0.11.11"
quote = "0.3.15"
